extends Node

var artwork = ['res://assets/ai-img-0.jpg', 'res://assets/ai-img-1.jpg', 'res://assets/ai-img-2.jpg', 'res://assets/ai-img-3.jpg', 'res://assets/ai-img-4.jpg', 'res://assets/ai-img-5.jpg', 'res://assets/ai-img-6.jpg', 'res://assets/ai-img-7.jpg', 'res://assets/ai-img-8.jpg', 'res://assets/ai-img-9.jpg', 'res://assets/ai-img-10.jpg', 'res://assets/ai-img-11.jpg', 'res://assets/ai-img-12.jpg', 'res://assets/ai-img-13.jpg', 'res://assets/ai-img-14.jpg', 'res://assets/ai-img-15.jpg', 'res://assets/ai-img-16.jpg', 'res://assets/ai-img-17.jpg', 'res://assets/ai-img-18.jpg', 'res://assets/ai-img-19.jpg', 'res://assets/ai-img-20.jpg', 'res://assets/ai-img-21.jpg', 'res://assets/ai-img-22.jpg', 'res://assets/ai-img-23.jpg', 'res://assets/ai-img-24.jpg', 'res://assets/ai-img-25.jpg', 'res://assets/ai-img-26.jpg', 'res://assets/ai-img-27.jpg', 'res://assets/ai-img-28.jpg', 'res://assets/ai-img-29.jpg', 'res://assets/ai-img-30.jpg', 'res://assets/ai-img-31.jpg', 'res://assets/ai-img-32.jpg', 'res://assets/ai-img-33.jpg', 'res://assets/ai-img-34.jpg', 'res://assets/ai-img-35.jpg', 'res://assets/ai-img-36.jpg', 'res://assets/ai-img-37.jpg', 'res://assets/ai-img-38.jpg', 'res://assets/ai-img-39.jpg', 'res://assets/ai-img-40.jpg', 'res://assets/ai-img-41.jpg', 'res://assets/ai-img-42.jpg', 'res://assets/ai-img-43.jpg', 'res://assets/ai-img-44.jpg', 'res://assets/ai-img-45.jpg', 'res://assets/ai-img-46.jpg', 'res://assets/ai-img-47.jpg', 'res://assets/ai-img-48.jpg', 'res://assets/ai-img-49.jpg']
var art_prompts = {'res://assets/ai-img-0.jpg': 'Sunset', 'res://assets/ai-img-1.jpg': 'Love', 'res://assets/ai-img-2.jpg': 'Plastic bag', 'res://assets/ai-img-3.jpg': 'Harmony', 'res://assets/ai-img-4.jpg': 'Broken glass', 'res://assets/ai-img-5.jpg': 'Friendship', 'res://assets/ai-img-6.jpg': 'Rusty nail', 'res://assets/ai-img-7.jpg': 'Transcendence', 'res://assets/ai-img-8.jpg': 'Banana peel', 'res://assets/ai-img-9.jpg': 'Tranquility', 'res://assets/ai-img-10.jpg': 'Crumpled paper', 'res://assets/ai-img-11.jpg': 'Resilience', 'res://assets/ai-img-12.jpg': 'Discarded tire', 'res://assets/ai-img-13.jpg': 'Enlightenment', 'res://assets/ai-img-14.jpg': 'Empty bottle', 'res://assets/ai-img-15.jpg': 'Nostalgia', 'res://assets/ai-img-16.jpg': 'Ethereal', 'res://assets/ai-img-17.jpg': 'Caterpillar', 'res://assets/ai-img-18.jpg': 'Ephemeral', 'res://assets/ai-img-19.jpg': 'Dandelion', 'res://assets/ai-img-20.jpg': 'Serendipity', 'res://assets/ai-img-21.jpg': 'Raindrop', 'res://assets/ai-img-22.jpg': 'Paradigm', 'res://assets/ai-img-23.jpg': 'Pebble', 'res://assets/ai-img-24.jpg': 'Quintessence', 'res://assets/ai-img-25.jpg': 'Feather', 'res://assets/ai-img-26.jpg': 'Synergy', 'res://assets/ai-img-27.jpg': 'Dewdrop', 'res://assets/ai-img-28.jpg': 'Inspiration', 'res://assets/ai-img-29.jpg': 'Sunbeam', 'res://assets/ai-img-30.jpg': 'Epiphany', 'res://assets/ai-img-31.jpg': 'Wildflower', 'res://assets/ai-img-32.jpg': 'Metamorphosis', 'res://assets/ai-img-33.jpg': 'Pollen', 'res://assets/ai-img-34.jpg': 'Euphoria', 'res://assets/ai-img-35.jpg': 'Leaf', 'res://assets/ai-img-36.jpg': 'Eternity', 'res://assets/ai-img-37.jpg': 'Snowflake', 'res://assets/ai-img-38.jpg': 'Enigma', 'res://assets/ai-img-39.jpg': 'Butterfly', 'res://assets/ai-img-40.jpg': 'Essence', 'res://assets/ai-img-41.jpg': 'Ripple', 'res://assets/ai-img-42.jpg': 'Sublime', 'res://assets/ai-img-43.jpg': 'Acorn', 'res://assets/ai-img-44.jpg': 'Whimsical', 'res://assets/ai-img-45.jpg': 'Driftwood', 'res://assets/ai-img-46.jpg': 'Splendor', 'res://assets/ai-img-47.jpg': 'Seashell', 'res://assets/ai-img-48.jpg': 'Ineffable', 'res://assets/ai-img-49.jpg': 'Firefly'}
var art_values = {'res://assets/ai-img-0.jpg': 'Common', 'res://assets/ai-img-1.jpg': 'Valuable', 'res://assets/ai-img-2.jpg': 'Trash', 'res://assets/ai-img-3.jpg': 'Valuable', 'res://assets/ai-img-4.jpg': 'Trash', 'res://assets/ai-img-5.jpg': 'Valuable', 'res://assets/ai-img-6.jpg': 'Trash', 'res://assets/ai-img-7.jpg': 'Exceptional', 'res://assets/ai-img-8.jpg': 'Trash', 'res://assets/ai-img-9.jpg': 'Valuable', 'res://assets/ai-img-10.jpg': 'Trash', 'res://assets/ai-img-11.jpg': 'Valuable', 'res://assets/ai-img-12.jpg': 'Trash', 'res://assets/ai-img-13.jpg': 'Exceptional', 'res://assets/ai-img-14.jpg': 'Trash', 'res://assets/ai-img-15.jpg': 'Common', 'res://assets/ai-img-16.jpg': 'Exceptional', 'res://assets/ai-img-17.jpg': 'Common', 'res://assets/ai-img-18.jpg': 'Valuable', 'res://assets/ai-img-19.jpg': 'Common', 'res://assets/ai-img-20.jpg': 'Valuable', 'res://assets/ai-img-21.jpg': 'Common', 'res://assets/ai-img-22.jpg': 'Valuable', 'res://assets/ai-img-23.jpg': 'Common', 'res://assets/ai-img-24.jpg': 'Exceptional', 'res://assets/ai-img-25.jpg': 'Common', 'res://assets/ai-img-26.jpg': 'Valuable', 'res://assets/ai-img-27.jpg': 'Common', 'res://assets/ai-img-28.jpg': 'Valuable', 'res://assets/ai-img-29.jpg': 'Common', 'res://assets/ai-img-30.jpg': 'Exceptional', 'res://assets/ai-img-31.jpg': 'Common', 'res://assets/ai-img-32.jpg': 'Valuable', 'res://assets/ai-img-33.jpg': 'Common', 'res://assets/ai-img-34.jpg': 'Exceptional', 'res://assets/ai-img-35.jpg': 'Common', 'res://assets/ai-img-36.jpg': 'Exceptional', 'res://assets/ai-img-37.jpg': 'Common', 'res://assets/ai-img-38.jpg': 'Valuable', 'res://assets/ai-img-39.jpg': 'Common', 'res://assets/ai-img-40.jpg': 'Valuable', 'res://assets/ai-img-41.jpg': 'Common', 'res://assets/ai-img-42.jpg': 'Exceptional', 'res://assets/ai-img-43.jpg': 'Common', 'res://assets/ai-img-44.jpg': 'Valuable', 'res://assets/ai-img-45.jpg': 'Common', 'res://assets/ai-img-46.jpg': 'Valuable', 'res://assets/ai-img-47.jpg': 'Common', 'res://assets/ai-img-48.jpg': 'Exceptional', 'res://assets/ai-img-49.jpg': 'Common'}

var more_prompts := ["Radiance", "Candy wrapper", "Solitude", "Nirvana", "Dust bunny", "Serenity", "Broken pencil", "Reverie", "Crumpled tissue", "Enchantment", "Stained cloth", "Melancholy", "Chipped mug", "Euphony", "Lint ball", "Intuition", "Rusted key", "Effervescence", "Tarnished coin", "Felicity", "Elysium", "Waning moon", "Quintessential", "Drifting cloud", "Ineffable", "Meandering stream", "Sanctuary", "Fallen autumn leaf", "Ethereal", "Cobweb", "Sublime", "Withered rose", "Epiphany", "Dandelion seed", "Elysian", "Morning dew", "Immaculate", "Feather float", "Quintessence", "Zephyr", "Ambrosia", "Firefly trail", "Rapture", "Lone sailboat", "Resplendence", "Disheveled", "Zenith", "Rust stain", "Ineffable bliss", "Tumbleweed"]
var more_values := ["Valuable", "Trash", "Common", "Exceptional", "Trash", "Valuable", "Trash", "Valuable", "Trash", "Exceptional", "Trash", "Common", "Trash", "Valuable", "Trash", "Valuable", "Trash", "Valuable", "Trash", "Valuable", "Exceptional", "Common", "Exceptional", "Common", "Exceptional", "Common", "Valuable", "Common", "Exceptional", "Common", "Exceptional", "Common", "Exceptional", "Common", "Exceptional", "Common", "Valuable", "Common", "Exceptional", "Common", "Valuable", "Common", "Exceptional", "Common", "Valuable", "Common", "Valuable", "Trash", "Exceptional", "Common"]

func generate_new():
	var prompt = more_prompts.pop_front()
	var value = more_values.pop_front()
	
	AILoop.generate_image_from_prompt(prompt)
	
	await get_tree().create_timer(10).timeout
	
	var img: Sprite2D = AILoop.gen_img
	#img.texture.get_da
	# todo: save the img to file and add to list

func remove_first():
	artwork.pop_front()
	generate_new()
